//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public byte BrokerID { get; set; }
        public string BrokerName { get; set; }
        public string FSPLicence { get; set; }
        public string CompRegNo { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PCode { get; set; }
        public bool RegVat { get; set; }
        public string VATNumber { get; set; }
        public string Telephone { get; set; }
        public string FAX { get; set; }
        public string WorkDir { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    }
}
