//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Policies = new HashSet<Policy>();
        }
    
        public int ClientNo { get; set; }
        public string Name { get; set; }
        public string Initials { get; set; }
        public string Title { get; set; }
        public string Salutation { get; set; }
        public string VatNo { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Language { get; set; }
        public string IdentityNo { get; set; }
        public string BusinessPhone { get; set; }
        public string HomePhone { get; set; }
        public string Fax { get; set; }
        public string CellPhone { get; set; }
        public string Contact { get; set; }
        public string Referral { get; set; }
        public Nullable<bool> MarriedFlag { get; set; }
        public Nullable<bool> GroupFlag { get; set; }
        public Nullable<bool> VIPFlag { get; set; }
        public Nullable<bool> LifeClient { get; set; }
        public Nullable<bool> PrintFlag { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ICollection<Policy> Policies { get; set; }
    }
}
