//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorpPolicyEntities : DbContext
    {
        public CorpPolicyEntities()
            : base("name=CorpPolicyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Broker> Brokers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<HttpRequestLog> HttpRequestLogs { get; set; }
        public virtual DbSet<Insurer> Insurers { get; set; }
        public virtual DbSet<Mask> Masks { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PolicyBank> PolicyBanks { get; set; }
        public virtual DbSet<PolicyDebit> PolicyDebits { get; set; }
        public virtual DbSet<PolicyDebitRisk> PolicyDebitRisks { get; set; }
        public virtual DbSet<PolicyRisk> PolicyRisks { get; set; }
        public virtual DbSet<PolicyType> PolicyTypes { get; set; }
        public virtual DbSet<RiskType> RiskTypes { get; set; }
        public virtual DbSet<VATData> VATDatas { get; set; }
    }
}
