//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDebit
    {
        public PolicyDebit()
        {
            this.PolicyDebitRisks = new HashSet<PolicyDebitRisk>();
        }
    
        public int DebitID { get; set; }
        public int PolicyID { get; set; }
        public short InsurerID { get; set; }
        public byte DebitReason { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ACBDate { get; set; }
        public System.DateTime BookDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public decimal BrokerFee { get; set; }
        public decimal AdminFee { get; set; }
    
        public virtual Insurer Insurer { get; set; }
        public virtual Policy Policy { get; set; }
        public virtual ICollection<PolicyDebitRisk> PolicyDebitRisks { get; set; }
    }
}
