//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDebitRisk
    {
        public int DebitRiskID { get; set; }
        public int DebitID { get; set; }
        public int RiskID { get; set; }
        public byte RiskReason { get; set; }
        public decimal Premium { get; set; }
        public decimal Commission { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual PolicyDebit PolicyDebit { get; set; }
    }
}
