//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyRisk
    {
        public int PolicyRiskID { get; set; }
        public int PolicyID { get; set; }
        public short RiskTypeID { get; set; }
        public decimal Insured { get; set; }
        public decimal Premium { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string Description { get; set; }
        public string LongDescription { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual RiskType RiskType { get; set; }
    }
}
