//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public Policy()
        {
            this.PolicyDebits = new HashSet<PolicyDebit>();
            this.PolicyRisks = new HashSet<PolicyRisk>();
        }
    
        public int PolicyID { get; set; }
        public string PolicyNo { get; set; }
        public int ClientNo { get; set; }
        public short InsurerID { get; set; }
        public byte PolicyTypeID { get; set; }
        public bool Cancelled { get; set; }
        public System.DateTime InceptionDate { get; set; }
        public byte AnnivMonth { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public byte Frequeny { get; set; }
        public string Insured { get; set; }
        public decimal AdminFee { get; set; }
        public decimal BrokerFee { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Insurer Insurer { get; set; }
        public virtual PolicyType PolicyType { get; set; }
        public virtual PolicyBank PolicyBank { get; set; }
        public virtual ICollection<PolicyDebit> PolicyDebits { get; set; }
        public virtual ICollection<PolicyRisk> PolicyRisks { get; set; }
    }
}
