//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpPolicy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskType
    {
        public RiskType()
        {
            this.PolicyRisks = new HashSet<PolicyRisk>();
        }
    
        public short RiskTypeID { get; set; }
        public string RiskTypeNo { get; set; }
        public string Description { get; set; }
        public decimal CommissionPerc { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ICollection<PolicyRisk> PolicyRisks { get; set; }
    }
}
